### ISSUE TITLE
PDFiumSharp 1.1.3 crashes while accessing pdfium_x64.dll on windows 7

### ISSUE THREAD

**Issue by vonzshik** [Zubastic/PDFiumSharp#6]
Started after upgrading from 1.0.1 to 1.1.3. Just the usual app crash with no stacktrace. Might be due to pdfium update.
Will this library continue to support windows 7 or do we have to make our own fork? Thanks in advance!

**Comment by alser** [comment]
There were no crashes using 1.1.2 either 🤔

**Comment by alser** [comment]
my bad, previous version was named 1.0.1, I meant it

**Comment by Zubastic** [comment]
> Will this library continue to support windows 7 or do we have to make our own fork? Thanks in advance!

Google dropped support for windows 7 in early 2023. So here no support at pdfium binaries.

https://support.google.com/chrome/thread/185534985/sunsetting-support-for-windows-7-8-8-1-and-windows-server-2012-and-2012-r2-in-early-2023?hl=en
